- name: installing "{{ component }}" server
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install "{{ component }}" 
  ansible.builtin.dnf:
    name: mongodb-org
    state: present

- name: Enable and start the service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes
  
- name: Allowing remote connection 
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  
- name: restart the "{{ component }}"
  ansible.builtin.service:
    name: mongod
    state: restarted